# Generated by Django 3.2.1 on 2021-07-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=200, verbose_name='the name of the food item')),
                ('foodLocation', models.CharField(max_length=3, verbose_name='the location of any food items')),
                ('foodItemNotes', models.CharField(max_length=300, verbose_name='any other notes about the food items')),
            ],
        ),
        migrations.CreateModel(
            name='foodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodLocation', models.CharField(max_length=3, verbose_name='the location of any food items')),
                ('stockNumber', models.PositiveIntegerField(verbose_name='the number of food items')),
                ('foodItemss', models.ManyToManyField(to='ffdb.foodItems')),
            ],
        ),
    ]
