# Generated by Django 3.2.1 on 2021-08-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='foodItemNotes',
            field=models.CharField(blank=True, max_length=300, verbose_name='any other notes about the food item'),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='foodLocation',
            field=models.CharField(max_length=3, verbose_name='the location of the food item'),
        ),
        migrations.AlterField(
            model_name='foodstock',
            name='foodLocation',
            field=models.CharField(max_length=3, verbose_name='the location of the food item'),
        ),
    ]
